import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // The service-role key bypasses RLS: only route handlers and server modules may import it
  {
    files: ["components/**", "hooks/**", "lib/api/**", "app/**/page.tsx", "app/**/layout.tsx", "proxy.ts"],
    rules: {
      "no-restricted-imports": ["error", { patterns: [{ group: ["**/supabase/admin", "@/lib/supabase/admin"], message: "Service-role client is server-only. Use it from route handlers." }] }],
    },
  },
  // Production code must never import test fixtures (they hold made-up data for tests only)
  {
    files: ["app/**", "components/**", "hooks/**", "lib/**", "emails/**", "proxy.ts"],
    ignores: ["**/*.test.ts", "**/*.test.tsx"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            { group: ["**/supabase/admin", "@/lib/supabase/admin"], message: "Service-role client is server-only. Use it from route handlers." },
            { group: ["**/tests/**", "@/tests/**", "**/fixtures", "**/fixtures/**"], message: "App code can't import from tests/ or fixtures. Fixtures are for tests only." },
          ],
        },
      ],
    },
  },
  // ...which is exactly where the service-role client belongs (fixtures stay banned)
  {
    files: ["app/**/route.ts", "lib/server/**"],
    ignores: ["**/*.test.ts"],
    rules: {
      "no-restricted-imports": ["error", { patterns: [{ group: ["**/tests/**", "@/tests/**", "**/fixtures", "**/fixtures/**"], message: "App code can't import from tests/ or fixtures. Fixtures are for tests only." }] }],
    },
  },
  {
    rules: { "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }] },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by Playwright
    "playwright-report/**",
    "test-results/**",
  ]),
]);

export default eslintConfig;
