/**
 * The Worker Cloudflare runs: OpenNext's generated Next.js handler, plus the cron trigger
 * (wrangler.jsonc) that re-checks custom domains. The cron calls the app's own route, so the
 * check runs with the same code and settings as everything else.
 */
// Generated by `opennextjs-cloudflare build`, so it may not exist yet when type-checking
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import { default as handler } from "./.open-next/worker.js";

// Just the shapes used here, so the app doesn't need the Workers runtime types
interface Env {
  CRON_SECRET?: string;
  [key: string]: unknown;
}
interface Ctx {
  waitUntil(p: Promise<unknown>): void;
}
interface NextHandler {
  fetch(req: Request, env: Env, ctx: Ctx): Response | Promise<Response>;
}
const next = handler as NextHandler;

const worker = {
  fetch: next.fetch,
  async scheduled(_event: unknown, env: Env, ctx: Ctx) {
    if (!env.CRON_SECRET) return console.warn("[cron] CRON_SECRET isn't set, so custom domains aren't re-checked on a schedule");
    const req = new Request("https://powerproof.internal/api/cron/domains", { headers: { authorization: `Bearer ${env.CRON_SECRET}` } });
    ctx.waitUntil(
      Promise.resolve(next.fetch(req, env, ctx)).then(async (res) => {
        if (!res.ok) console.error("[cron] domain check answered", res.status, await res.text().catch(() => ""));
      })
    );
  },
};

export default worker;
